version: '2'

services:
  mysqldb:
    image: mysql:5.7
    networks:
      - mysql
    environment:
      MYSQL_DATABASE: 'devops'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"

  devops_backend:
    depends_on:
      - mysqldb
    ports:
      - "8082:8082"
    networks:
      - mysql
    image: devops

networks:
  mysql:
